version: '3'

services: #containers

########################### PHP ###########

  php_library:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: php_library
    volumes:
      - ./:/var/www/library
      - ./docker/xdebug/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

    working_dir: /var/www/library
    networks:
      - library_network

########### SERVER ########################
#
  nginx_library:
    image: nginx:latest
    container_name: nginx_library
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/library
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - library_network
    expose:
      - 8000

############################## Data Base ###########
  postgresql_library:
    build:
      context: ./docker/db_conf
      dockerfile: Dockerfile
    container_name: postgresql_library
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
    restart: unless-stopped
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    tty: true
    networks:
      - library_network
    expose:
      - 5432

  ######################## COMPOSER #########

  composer_library:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    container_name: composer_library
    volumes:
      - ./:/var/www/library
      - ./docker/composer/cache:/root/.composer/cache
    working_dir: /var/www/library
    depends_on:
      - php_library
    networks:
      - library_network

  ################## ARTISAN ##############

  artisan_library:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: artisan_library
    volumes:
      - ./:/var/www/library
    depends_on:
      - postgresql_library
      - composer_library
    working_dir: /var/www/library
    entrypoint: ["php", "artisan"]
    command: ["queue:work"]
    restart: always
    networks:
      - library_network

networks:
  library_network:
    external: true
